services:
  auth:
    name: Auth Service
    host: 127.0.0.1
    port: 8002
    path: auth-service
    app: app.main:app
    health: /health

  student:
    name: Student Service
    host: 127.0.0.1
    port: 8001
    path: student-service
    app: app.main:app
    health: /health

  document:
    name: Document Service
    host: 127.0.0.1
    port: 8003
    path: document-service
    app: app.main:app
    health: /health

  ai:
    name: AI Service
    host: 127.0.0.1
    port: 8099
    path: Mock_ai_server
    app: app.main:app
    health: /health